import neostandard from 'neostandard'

export default [
  ...neostandard({
    ts: true,
    env: ['browser', 'node'],
    ignores: [
      'dist/**',
      'obj/**',
      'src/bbs_c.js', // generated by make wasm
      'test/test.js', // generated by tsc
      'browser/bbs.js', // generated by webpack
      'browser/demo.js' // generated by webpack
    ]
  }),
  {
    rules: {
      // allow the g_ prefix for global variables in addition to standard's default
      camelcase: ['error', { allow: ['^UNSAFE_', '^g_'], properties: 'never', ignoreGlobals: true }]
    }
  }
]
